{
    'name': 'Custom CRM - Assurance santé',
    'version': '12.0.0.0.1',
    'summary': 'Show your offer reports',
    'author': 'WAHBI ACHRAF',
    'maintainer': 'WAHBI ACHRAF',
    'Company': 'GetapPRO',
    'website': 'https://www.getap.pro',
    'depends': ['crm'],
    'license': 'LGPL-3',
    'category': 'Sales',
    'data':[
        'views/assurance_sante.xml',
    ],
    #'images': ['static/description/sale-report-banner.png'],
    'price': 0.0,
    'currency': 'EUR',
    'installable': True,
    'auto_install': False,
    'application': False,
    'sequence': 5,
}
